import Head from 'next/head';
import { useState } from 'react';
// import YouTubeSubtitleViewer from '@/components/YouTubeSubtitleViewer';
// import CaptionExtractor from '@/components/CaptionExtractor';
import YoutubeCaptions from '@/components/YoutubeCaptions';
import NewVideo from '@/components/NewVideo';
import VideoChat from '@/components/VideoChat';

export default function Home() {
  const videoURL = 'https://youtu.be/G8xSr7Q8MGY';
  const [summary, setSummary] = useState('');
  const [title, setTitle] = useState('');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {title && summary ? (
          <VideoChat title={title} summary={summary} />
        ) : (
          <NewVideo setTitle={setTitle} setSummary={setSummary} />
        )}
      </main>
    </>
  );
}
