import Head from 'next/head';
// import YouTubeSubtitleViewer from '@/components/YouTubeSubtitleViewer';
// import CaptionExtractor from '@/components/CaptionExtractor';
import YoutubeCaptions from '@/components/YoutubeCaptions';

export default function Home() {
  const videoURL = 'https://youtu.be/G8xSr7Q8MGY';

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {/* <YouTubeSubtitleViewer videoURL='https://youtu.be/R8mnOOuK85M' /> */}
        {/* <CaptionExtractor /> */}

        <YoutubeCaptions videoURL={videoURL} />
      </main>
    </>
  );
}

// export async function getServerSideProps(context) {
//   const code = context.query.code;
//   return {
//     props: { code },
//   };
// }
